In [2]:
import pandas as pd
from pathlib import Path

# Go up one level from /notebooks to repo root
ROOT = Path.cwd().parent

CLEANED = ROOT / "data" / "processed" / "02_cleaned"

df = pd.read_csv(CLEANED / "perceived_mh_annual.csv")
df.head()

,ref_date,geo,dguid,age_group,sex,indicator,characteristic,uom,uom_id,scalar_factor,scalar_id,vector,coordinate,value,status
0,2019/2020,Newfoundland and Labrador,2021A000210,"Total, 18 years and over",Both sexes,"Perceived mental health, very good or excellent",Percent,Percent,239,units,0,v1806947204,2.1.1.3.4,68.6,NaN
1,2021/2022,Newfoundland and Labrador,2021A000210,"Total, 18 years and over",Both sexes,"Perceived mental health, very good or excellent",Percent,Percent,239,units,0,v1806947204,2.1.1.3.4,58.3,NaN
2,2023/2024,Newfoundland and Labrador,2021A000210,"Total, 18 years and over",Both sexes,"Perceived mental health, very good or excellent",Percent,Percent,239,units,0,v1806947204,2.1.1.3.4,53.5,NaN
3,2019/2020,Newfoundland and Labrador,2021A000210,"Total, 18 years and over",Both sexes,"Perceived mental health, fair or poor",Percent,Percent,239,units,0,v1806947211,2.1.1.4.4,8.0,NaN
4,2021/2022,Newfoundland and Labrador,2021A000210,"Total, 18 years and over",Both sexes,"Perceived mental health, fair or poor",Percent,Percent,239,units,0,v1806947211,2.1.1.4.4,13.2,NaN

In [4]:
df.shape

(936, 15)

In [5]:
df.columns

Index(['ref_date', 'geo', 'dguid', 'age_group', 'sex', 'indicator',
       'characteristic', 'uom', 'uom_id', 'scalar_factor', 'scalar_id',
       'vector', 'coordinate', 'value', 'status'],
      dtype='str')

In [7]:
df.dtypes

ref_date              str
geo                   str
dguid                 str
age_group             str
sex                   str
indicator             str
characteristic        str
uom                   str
uom_id              int64
scalar_factor         str
scalar_id           int64
vector                str
coordinate            str
value             float64
status                str
dtype: object

In [9]:
df.sample(5)

,ref_date,geo,dguid,age_group,sex,indicator,characteristic,uom,uom_id,scalar_factor,scalar_id,vector,coordinate,value,status
31,2021/2022,Newfoundland and Labrador,2021A000210,"Total, 18 years and over",Males,"Perceived life stress, most days quite a bit o...",Percent,Percent,239,units,0,v1806947393,2.1.2.5.4,15.8,NaN
227,2023/2024,New Brunswick,2021A000213,"Total, 18 years and over",Both sexes,Mood disorder,Percent,Percent,239,units,0,v1806983760,15.1.1.11.4,15.7,NaN
884,2023/2024,Nunavut,2021A000262,"Total, 18 years and over",Both sexes,Heavy drinking,Percent,Percent,239,units,0,v1807274721,116.1.1.19.4,21.0,NaN
274,2021/2022,New Brunswick,2021A000213,"Total, 18 years and over",Females,Mood disorder,Percent,Percent,239,units,0,v1806984096,15.1.3.11.4,15.7,NaN
425,2023/2024,Ontario,2021A000235,"Total, 18 years and over",Females,"Cannabis use, past 12 months",Percent,Percent,239,units,0,v1807056394,40.1.3.15.4,18.3,NaN

In [10]:
df.isna().sum()

ref_date            0
geo                 0
dguid               0
age_group           0
sex                 0
indicator           0
characteristic      0
uom                 0
uom_id              0
scalar_factor       0
scalar_id           0
vector              0
coordinate          0
value              26
status            898
dtype: int64